title: Angela's portfolio
description: My portfolio
theme: just-the-docs

url: https://shuangela.github.io/portfolio

aux_links:
  Email: mailto:angelashu103@gmail.com
  LinkedIn: https://www.linkedin.com/in/angela-shu/
